apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_URLS: http://+:8080;http://+:7777  
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip;Port=5432;User ID=postgres;Password=postgrespw;Database=auctions
  IdentityService__Authority: http://identity-clusterip:8080
  Kestrel__Endpoints__Grpc__Protocols: Http2
  Kestrel__Endpoints__Grpc__Url: http://+:7777
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: http://+:8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:  
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
  ConnectionStrings__MongoDbConnection: mongodb://root:mongopw@mongo-clusterip
  AuctionServiceUrl: http://auction-clusterip:8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-config
data:            
  ASPNETCORE_URLS: http://+:8080
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip;Port=5432;User ID=postgres;Password=postgrespw;Database=identity
  IssuerUrl: https://id.carsties.com
  RedirectUris__Clients__NextApp: https://app.carsties.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bid-svc-config
data:            
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip;Port=5432;User ID=postgres;Password=postgrespw;Database=bids
  IdentityService__Authority: http://identity-clusterip:8080
  GrpcAuction: http://auction-clusterip:7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-svc-config
data:
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
data:
  ClientApp: https://app.carsties.com
  IdentityService__Authority: http://identity-clusterip:8080
