apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: yiliangzheng0729/carsties-gateway-svc
        imagePullPolicy: Never        
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: gateway-svc-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
  - port: 8080
    targetPort: 8080
                        
