apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-depl
spec:
  selector:
    matchLabels:
      app: identity-svc
  template:
    metadata:
      labels:
        app: identity-svc
    spec:
      containers:
      - name: identity-svc
        image: yiliangzheng0729/carsties-identity-svc
        imagePullPolicy: Never        
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
          name: identity-svc-config
---
apiVersion: v1
kind: Service
metadata:
  name: identity-clusterip
spec:
  type: ClusterIP
  selector:
    app: identity-svc
  ports:
  - port: 8080
    targetPort: 8080
          
