apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
spec:
  selector:
    matchLabels:
      app: notification-svc
  template:
    metadata:
      labels:
        app: notification-svc
    spec:
      containers:
      - name: notification-svc
        image: yiliangzheng0729/carsties-notification-svc
        imagePullPolicy: Never        
        envFrom:
        - configMapRef:
            name: notification-svc-config
        ports:
        - containerPort: 8080
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: notification-clusterip
spec:
  type: ClusterIP
  selector:
    app: notification-svc  
  ports:
  - port: 8080
    targetPort: 8080
    name: web
          