apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  namespace: carsties
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
