apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine        
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: rabbit
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                key: password
                name: rabbitmq-secret
        ports:
          - containerPort: 5672
            name: rabbitmq-port
          - containerPort: 15672
            name: mgmt-port
        volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmqdata
      volumes:
        - name: rabbitmqdata
          persistentVolumeClaim: 
            claimName: rabbitmq-claim
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-np
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 30002